# Generated by Django 2.0.6 on 2018-06-24 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articulateworks', '0002_application_contract_proposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='merchant_email',
            field=models.EmailField(default='info@articulateresearch.com', help_text='PayPal Merchant Email', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requester',
            name='merchant_email',
            field=models.EmailField(default='info@articulateresearch.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicantrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicantskill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicanttask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requesterrole',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_set', to='articulateworks.Requester'),
        ),
        migrations.AlterField(
            model_name='requesterskill',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_set', to='articulateworks.Requester'),
        ),
        migrations.AlterField(
            model_name='requestertask',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_set', to='articulateworks.Requester'),
        ),
    ]
