# Generated by Django 2.0.6 on 2018-06-24 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articulateworks', '0003_auto_20180624_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='requesters',
            field=models.ManyToManyField(related_name='requester_roles', through='articulateworks.RequesterRole', to='articulateworks.Requester'),
        ),
        migrations.AddField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(related_name='applicant_roles', through='articulateworks.ApplicantRole', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skill',
            name='requesters',
            field=models.ManyToManyField(related_name='requester_skills', through='articulateworks.RequesterSkill', to='articulateworks.Requester'),
        ),
        migrations.AddField(
            model_name='skill',
            name='users',
            field=models.ManyToManyField(related_name='applicant_skills', through='articulateworks.ApplicantSkill', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='requesters',
            field=models.ManyToManyField(related_name='requester_tasks', through='articulateworks.RequesterTask', to='articulateworks.Requester'),
        ),
        migrations.AddField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(related_name='applicant_tasks', through='articulateworks.ApplicantTask', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requester',
            name='admins',
            field=models.ManyToManyField(related_name='requester_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requesterrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requesterrole_set', to='articulateworks.Role'),
        ),
        migrations.AlterField(
            model_name='requesterskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requesterskill_set', to='articulateworks.Skill'),
        ),
        migrations.AlterField(
            model_name='requestertask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestertask_set', to='articulateworks.Task'),
        ),
    ]
